# Terraform Provider testing workflow.
name: Collibra Data Access Terraform Provider - Acceptance tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

env:
  GOPRIVATE: github.com/collibra/data-access-go-sdk

jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup private repo access
        run: |
          git config --global url.https://${GH_ACCESS_TOKEN}@github.com/.insteadOf https://github.com/
        env:
          GH_ACCESS_TOKEN: ${{ secrets.COLLIBRA_GITHUB_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "go.sum"
          check-latest: true
          cache: true

      - name: Mod Tidy
        run: go mod tidy

      - name: Build
        run: go build -v .

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.11.3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_PUBLIC_API_KEY }}
          SONAR_HOST_URL: https://sonarqube.collibra.dev
        with:
          args: >
            -Dsonar.pullrequest.github.repository=collibra/go-set    

      - name: FOSSA Scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_PUBLIC_API_KEY }}

  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup private repo access
        run: |
          git config --global url.https://${GH_ACCESS_TOKEN}@github.com/.insteadOf https://github.com/
        env:
          GH_ACCESS_TOKEN: ${{ secrets.COLLIBRA_GITHUB_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "go.sum"
          check-latest: true
          cache: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Mod Tidy
        run: go mod tidy

      - name: Generate
        run: go generate ./...

      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  # Run acceptance tests in a matrix with Terraform CLI versions
  test:
    name: Terraform Provider Acceptance Tests
    needs:
      - build
      - generate
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '1.10.*'
          - '1.11.*'
          - '1.12.*'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup private repo access
        run: |
          git config --global url.https://${GH_ACCESS_TOKEN}@github.com/.insteadOf https://github.com/
        env:
          GH_ACCESS_TOKEN: ${{ secrets.COLLIBRA_GITHUB_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "go.sum"
          check-latest: true
          cache: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Download
        run: go mod download

      - name: Acceptance tests
        env:
          TF_ACC: "1"
          TF_VAR_collibra_user: ${{ secrets.COLLIBRA_USER }}
          TF_VAR_collibra_secret: ${{ secrets.COLLIBRA_SECRET }}
          TF_VAR_collibra_url: ${{ secrets.COLLIBRA_URL }}
        run: go test -v -cover ./internal/ -timeout 0
        timeout-minutes: 15